MeshConv is now ported to Charm++
While the functionality in MeshConv (conversion of meshes) would not require a
parallel run, still converted to Charm++ as the other ingredients, require
Charm++. An example is the tagged tuple which has pack/unpack routines.

The executable can be run with or without charmrun, and on arbitrary number of
PEs: only the main chare will be created and a single serial conversion will
take place at this time.

Tried to make meshconv not use Charm++ as it would not be explicitly required,
but ran into linking problems such as

/home/jbakosi/code/quinoa/tpl/install/clang/charm/bin/../lib/libck.a(init.o): In function `_initCharm(int, char**)':
/home/jbakosi/code/quinoa/tpl/install/clang/charm/mpi-linux-x86_64-mpicxx/tmp/init.C:1164: undefined reference to `CkRegisterMainModule'

Though the charmc wrapper should (and probably does) work for non-Charm
executables (according to the Charm++ documentation), the additional
dependencies on Charm++, such as tagged tuple, probably pulls in the above
ckRegisterMainModule. So just converted meshconv to Charm++. It may come in
handy for large meshes anyway in future.

Also, we now globally overwrite the linker command in cmake's
CMAKE_CXX_LINK_EXECUTABLE to charmc, which somewhat unfortunately forces all
executables to be linked with charmc. I don't really like this, but I see no
good work-around this minor nuisance at this time. The older option, hijacking
the link line with a script and replace the linker would work for a single
executable, but only works for makefile generators and does not work with ninja.

Other details:

  * Handler.[Ch] now moved to directory Main/ - more approriate there. This
    also eliminates the separate add_dependencies cmake code for Base, as
    Handler is now part of the executables (rngtest and meshconv) directly,
    which are Charm++ modules and thus have the dependencies setup
    automatically.

  * Control/Grammar.h now does not depend on any hard-coded keywords. This was
    the case with keyword 'end', but not all parsers need to depend on this.
    So now the couple of items, 'block' and 'vector' in the generic grammar
    are templated on the the end-keyword. This is updated in quinoa's grammar
    as well, but not tested.

  * Add verbose command line option for meshconv.

  * Add extra dependency of RNGTest on rngtestCharmModule. This is required as
    one of the dependencies of RNGTest, e.g., TestU01Suite, refers to the main
    Charm++ proxy defined in the Charm++ module rngtest (in Main/RNGTest.C). If
    this is not done, rngtest.decl.h may not be available before TestU01Suite.C
    is compiled, leading to an error.