Fixes to libstdc++ vs libc++ build options
As it turns out switching between libstdc++ and libc++ has never worked as
originally intended:
 - the TPL build never really switched to libc++ even when was configured to do
   so with cmake because it was setting the wrong internal cmake variable, and
 - the gnu build used the wrong command line argument (that gcc just ignored)
   for switching to libc++ so it never ended up using libc++.

With these fixes now switching works:
 * In the TPL build all TPLs that use the C++ compiler will use the correct
   standard library configured (libstdc++ or libc++).
 * For the gnu compiler we do not offer the choice any longer, because there is
   not an easy way to switch to libc++ for gnu. Gnu will use libstdc++ by
   default and that's it.
 * Clang and Intel can successfully switch between the two and this has been
   tested: Clang works with both, however, Intel breaks with both at this time,
   but I doubt due to the issue of switching between libstdc++ and libc++. I
   have not tested with intel for quite a long time, and the following problem
   seems to point to intel's problem with standard compliance regarding the STL:

   /home/jbakosi/code/quinoa/src/Base/ContainerUtil.h(124): error: identifier "cbegin" is undefined
   std::transform( cbegin(src), cend(src), begin(dst), begin(dst),
                    ^
          detected during:
   So we'll commit this for now, but will have to work on the intel build.